### ISSUE TITLE
Add auto execution for .sql/.sh at start of the container

### ISSUE THREAD

**Issue by IceflowRE** [linuxserver/docker-mariadb-arm64#6]
The official mysql images are supporting this option:
https://hub.docker.com/_/mysql/
See chapter `Using a custom MySQL configuration file`

**Comment by sparklyballs** [comment]
we already have that 

https://github.com/linuxserver/docker-mariadb-arm64#setting-up-the-application

**Comment by IceflowRE** [comment]
I have to place them inside `/config`?
